on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: node:alpine
    steps:
      - run: apk add --update git
      - run: git clone ${{ github.repository }} --branch=${{ github.ref }} --depth 1
      - run: npm ci
      - run: npm run test
